version: '2'
services:
  app:
    build:
      context: ./docker-compose
      args:
        host_uid: $UID
        host_gid: $GID
    # your local image with correct permissions
    image: $USER/scipy-notebook:$UID.$GID
    environment:
      JOBLIB_TEMP_FOLDER: /tmp
    working_dir: /workdir
    volumes:
      - .:/workdir

  jupyter:
    extends: app
    command: jupyter notebook
    ports:
      - 8888:8888

  jupyterlab:
    extends: app
    command: jupyter lab --ip=0.0.0.0
    ports:
      - 8888:8888
