version: '3.8'
services:
  app:
    image: jupyter/scipy-notebook
    command: jupyter lab
    user: "${CONTAINER_USER}"
    group_add:
      - users
    environment:
      JOBLIB_TEMP_FOLDER: /tmp
      PYTHONUSERBASE: /workdir/.pip
      PYTHONDONTWRITEBYTECODE: 1
      PATH: "/workdir/.pip/bin/:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      TMPDIR: /workdir/tmp
    working_dir: /workdir
    volumes:
      - .:/workdir
    ports:
      - 127.0.0.1:8888:8888
